pilz_industrial_motion_planner:
  planning_plugin: pilz_industrial_motion_planner/CommandPlanner
  request_adapters: >-
    default_planner_request_adapters/ResolveConstraintFrames
    default_planner_request_adapters/ValidateWorkspaceBounds
    default_planner_request_adapters/CheckStartStateBounds
    default_planner_request_adapters/CheckStartStateCollision
  start_state_max_bounds_error: 0.1