hiwin_tf_tree_publisher:
  ros__parameters:
    world_frame: world
    base_frame: base_link
    flange_frame: flange
    tool_frame: tool7
    camera_frame: camera_link
    apriltag_frame: apriltag

    # 當 /apriltag/pose_camera 的 header.frame_id 為空時使用
    apriltag_fallback_parent_frame: camera_color_optical_frame

    # HIWIN CHECK_POSE 角度轉換
    hiwin_euler_order: xyz
    hiwin_tool_number: 0
    hiwin_base_number: 0

    publish_rate_hz: 10.0
    apriltag_print_rate_hz: 5.0

    # world -> base_link
    world_to_base_xyz_m: [0.0, 0.0, 0.0]
    world_to_base_rpy_deg: [0.0, 0.0, 0.0]

    # flange -> tool7
    flange_to_tool_xyz_m: [0.005087, -0.005525, 0.191133]
    flange_to_tool_rpy_deg: [0.0, 0.0, 0.0]

    # tool7 -> camera_link
    tool_to_camera_xyz_m: [0.03068762615, 0.11368722386, -0.09130355460]

    tool_to_camera_quat_xyzw:
      [
        0.002874781996797597,
        -0.3562352693857901,
        0.9341205845947474,
        0.022514482238590865
      ]